server:
  port: 9100 # 网关入口端口

File:
  uploadPath: ${FILE_UPLOADPATH:${user.home}/freshmall/upload}

spring:
  application:
    name: freshmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
      routes:
        # 用户服务路由
        - id: user_route
          uri: lb://freshmall-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        # 商品服务路由
        - id: thing_route
          uri: lb://freshmall-thing
          predicates:
            - Path=/api/thing/**, /api/classification/**, /api/thingCollect/**, /api/thingWish/**, /api/record/**
          filters:
            - StripPrefix=1

        # 订单服务路由
        - id: order_route
          uri: lb://freshmall-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1

  webflux:
    static-path-pattern: /api/staticfiles/**
  web:
    resources:
      static-locations: file:${File.uploadPath}
