server:
  port: 9201 # 用户服务端口

# 自定义文件上传路径
File:
  uploadPath: E:\test\ncp\freshmall\server\upload

spring:
  application:
    name: freshmall-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:9848

  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/freshmall_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1MB
      enabled: true

  # 静态资源映射 (Spring Boot 2.x)
  web:
    resources:
      static-locations: file:${File.uploadPath}
  mvc:
    static-path-pattern: /staticfiles/**

# 配置 MyBatis Plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
