#!/bin/bash

docker run -d \
--name nacos-server \
--network host \
-e MODE=standalone \
-e SPRING_DATASOURCE_PLATFORM=derby \
nacos/nacos-server:v2.4.3


docker run -d \
--name mysql-server \
--network host \
-e MYSQL_ROOT_PASSWORD=root \
-e MYSQL_DATABASE=freshmall_db \
mysql:8.0 \
--character-set-server=utf8mb4 \
--collation-server=utf8mb4_unicode_ci \
--default-time-zone=+08:00